FROM node:18-alpine AS builder

WORKDIR /app

# Copiar archivos de package.json primero
COPY package*.json ./

# Instalar dependencias
RUN npm i

# Copiar el resto del código fuente
COPY . .

# Construir la aplicación
RUN npm run build

# Etapa de producción
FROM node:18-alpine AS runner

WORKDIR /app

# Establecer entorno de producción
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

# Copiar archivos necesarios
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules

# Exponer el puerto
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]